# Generated by Django 4.1.3 on 2024-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_user_balance_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_update',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость продления'),
        ),
    ]
