# Generated by Django 4.1.3 on 2024-03-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_user_flesh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
