# Generated by Django 5.0.3 on 2024-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_flesh_tariff_remove_user_idf_remove_user_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='delay',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_license',
            field=models.CharField(choices=[('base', 'base'), ('premium', 'premium')], default=('base', 'base'), max_length=10),
        ),
        migrations.AlterField(
            model_name='flesh',
            name='IDF',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
