# Generated by Django 5.0.3 on 2024-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_tariff_delay_tariff_name_license_alter_flesh_idf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
