# Generated by Django 4.1.3 on 2024-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='flesh',
            name='is_use_user',
            field=models.BooleanField(default=False, verbose_name='Используется?'),
        ),
    ]
