# Generated by Django 4.1.3 on 2024-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_tariff_price_alter_tariff_price_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffbalances',
            name='data_start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
