# Generated by Django 4.1.3 on 2024-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_tariffbalances_data_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffbalances',
            name='count_change_key',
            field=models.IntegerField(default=0, verbose_name='Количество смены ключа'),
        ),
    ]
