# Generated by Django 5.0.3 on 2024-03-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_tariff_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flesh',
            options={'verbose_name': 'Флешка', 'verbose_name_plural': 'Флешки'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='flesh',
            name='IDF',
            field=models.CharField(max_length=500, verbose_name='ИДФ'),
        ),
        migrations.AlterField(
            model_name='flesh',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='delay',
            field=models.IntegerField(default=5, verbose_name='Задержка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='mess_ln',
            field=models.IntegerField(verbose_name='Длина сообщения'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='none', max_length=20, verbose_name='Название лицензии'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name_license',
            field=models.CharField(choices=[('base', 'base'), ('premium', 'premium')], default=('base', 'base'), max_length=10, verbose_name='Лицензия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flesh',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='server.flesh', verbose_name='Флешка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
