# Generated by Django 4.1.3 on 2024-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_tariffbalances_count_change_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffbalances',
            name='count_msg_user',
            field=models.IntegerField(default=0, verbose_name='Количество отправленных сообщений'),
        ),
    ]
