# Generated by Django 4.1.3 on 2024-03-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tariffbalances_count_msg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_dialog', models.CharField(max_length=100, verbose_name='Токен авторизации диалога')),
                ('s_key', models.CharField(max_length=1, verbose_name='Первый ключ(любой символ)')),
                ('f_key', models.CharField(max_length=1, verbose_name='Первый ключ(любой символ)')),
                ('image_key', models.ImageField(blank=True, null=True, upload_to='user/key/img_key/%Y/%m/%d/', verbose_name='Картинка')),
                ('is_active', models.BooleanField(verbose_name='Актуальный')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Индификация ключа',
                'verbose_name_plural': 'Индификация ключей',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Категория операции')),
                ('dsc', models.CharField(max_length=55, verbose_name='Комментарий')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Стоимость')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
            options={
                'verbose_name': 'Платежная операция',
                'verbose_name_plural': 'Платежные операции',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='identification_dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.keyidentification', verbose_name='Индификация диалога'),
        ),
        migrations.AddField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, to='server.payment', verbose_name='Платежные операции'),
        ),
    ]
