# Generated by Django 5.0.3 on 2024-03-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flesh',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flesh',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.tariff', verbose_name='Тариф'),
        ),
    ]
