# Generated by Django 4.1.3 on 2024-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_payment_category_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flesh',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_update',
            field=models.IntegerField(default=0, verbose_name='Стоимость продления'),
        ),
    ]
