# Generated by Django 5.0.4 on 2024-04-12 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0007_objidfdialog_user_connect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='идентификатор комнаты (должен быть уникальным)', max_length=255, null=True, unique=True, verbose_name='название')),
                ('created_at', models.DateTimeField(verbose_name='дата создания чата')),
                ('is_use', models.BooleanField(default=False, verbose_name='Используется')),
                ('host', models.ForeignKey(help_text='Создатель комнаты', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='server.objidfdialog', verbose_name='хозяин')),
            ],
            options={
                'verbose_name': 'Чатная комната',
                'verbose_name_plural': 'Чатные комнаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.room', verbose_name='чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
