# Generated by Django 5.0.3 on 2024-03-22 11:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_market', models.CharField(choices=[('on sale', 'В продаже'), ('popular', 'Популярный'), ('unavailable', 'Недоступен'), ('in processing', 'В обработке'), ('new', 'Новинка'), ('beneficial', 'Выгодный')], max_length=30, verbose_name='Маркетинговое положение')),
                ('name', models.CharField(default='none', max_length=20, verbose_name='Название лицензии')),
                ('count_msg', models.IntegerField(verbose_name='Количество сообщений')),
                ('count_dialog', models.IntegerField(default=1, verbose_name='Количество диалогов')),
                ('count_change_key', models.IntegerField(verbose_name='Количество смены ключа')),
                ('count_update_tariff', models.IntegerField(verbose_name='Количество обновления тарифа')),
                ('mess_ln', models.IntegerField(verbose_name='Длина сообщения')),
                ('delay', models.IntegerField(default=5, verbose_name='Задержка')),
                ('deg_protection', models.IntegerField(verbose_name='Степень защиты')),
                ('name_license', models.CharField(choices=[('base', 'Базовый'), ('professionale', 'Проффисиональный'), ('premium', 'Преимум')], default=('base', 'Базовый'), max_length=20, verbose_name='Лицензия')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость')),
                ('price_update', models.IntegerField(default=0, verbose_name='Стоимость продления')),
                ('coupon', models.CharField(max_length=20, verbose_name='Купон(только на преимум)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active_flesh', models.BooleanField(default=True, verbose_name='Активность аккаунта')),
                ('rif_token', models.CharField(blank=True, max_length=20, null=True, verbose_name='Реферальный токен')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/photo/%Y/%m/%d/', verbose_name='Фотография')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
