# Generated by Django 5.0.3 on 2024-03-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('purchase', 'Покупка'), ('update', 'Обновление'), ('purchase_bonuses', 'Оплата бонусами')], max_length=30, verbose_name='Категория операции')),
                ('dsc', models.CharField(max_length=55, verbose_name='Комментарий')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
            options={
                'verbose_name': 'Платежная операция',
                'verbose_name_plural': 'Платежные операции',
            },
        ),
        migrations.CreateModel(
            name='TariffBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_msg_user', models.IntegerField(default=0, verbose_name='Количество отправленных сообщений')),
                ('count_change_key', models.IntegerField(default=0, verbose_name='Количество смены ключа')),
                ('count_msg', models.IntegerField(verbose_name='Количество сообщений')),
                ('count_dialog', models.IntegerField(default=1, verbose_name='Количество диалогов')),
                ('count_update_tariff', models.IntegerField(verbose_name='Количество обновления тарифа')),
                ('data_start', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Баланс тарифа',
                'verbose_name_plural': 'Балансы тарифов',
            },
        ),
        migrations.CreateModel(
            name='Flesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDF', models.CharField(max_length=500, verbose_name='ИДФ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('is_use_user', models.BooleanField(default=False, verbose_name='Используется?')),
                ('count_flesh', models.IntegerField(default=0, verbose_name='Остаток флешек')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Флешка',
                'verbose_name_plural': 'Флешки',
            },
        ),
        migrations.AddField(
            model_name='usercustom',
            name='flesh',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.flesh', verbose_name='ID флешки'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, to='server.payment', verbose_name='Платежные операции'),
        ),
    ]
