# Generated by Django 5.0.3 on 2024-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_payment_tariffbalances_flesh_usercustom_flesh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_dialog', models.CharField(max_length=20, verbose_name='Токен авторизации диалога')),
                ('f_key', models.CharField(max_length=1, verbose_name='Первый ключ(любой смивол)')),
                ('s_key', models.CharField(max_length=3, verbose_name='Второй ключ(любая цифра)')),
                ('image_key', models.ImageField(blank=True, null=True, upload_to='user/key/img_key/%Y/%m/%d/', verbose_name='Картинка')),
                ('is_active', models.BooleanField(verbose_name='Актуальный')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Индификация ключа',
                'verbose_name_plural': 'Индификация ключей',
            },
        ),
        migrations.CreateModel(
            name='ObjIdfDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('connected', 'Подключено')], max_length=10, verbose_name='Статус')),
                ('is_use', models.BooleanField(default=False, verbose_name='Используется')),
                ('idf_dialog', models.ManyToManyField(to='server.keyidentification', verbose_name='Индификаторы пользователей')),
            ],
            options={
                'verbose_name': 'Объект IDF диалога',
                'verbose_name_plural': 'Объекты IDF диалога',
            },
        ),
    ]
