# Generated by Django 5.0.3 on 2024-03-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_keyidentification_objidfdialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='balance_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.tariffbalances', verbose_name='Остаток тарифа'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='identification_dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.objidfdialog', verbose_name='Объект индификации диалога'),
        ),
    ]
