# Generated by Django 5.0.3 on 2024-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_usercustom_balance_tariff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('new', 'Новинка'), ('product', 'О продукте'), ('support', 'О сервисе'), ('tariff', 'О тарифах')], max_length=20, verbose_name='Категория')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
