# Generated by Django 5.0.3 on 2024-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='status_idf',
            field=models.CharField(choices=[('not_connect', 'Не подключен'), ('waiting', 'В ожидании'), ('connected', 'Подключен')], default='not_connect', max_length=20, verbose_name='Статус подключения'),
        ),
    ]
