# Generated by Django 5.0.3 on 2024-03-22 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_usercustom_status_idf'),
    ]

    operations = [
        migrations.AddField(
            model_name='objidfdialog',
            name='user_connect',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
